FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add mariadb mariadb-client

RUN mkdir -p /run/mysqld/

# copy scrpt
RUN mkdir /files
COPY ./srcs_mysql/mysql_script.sh /files/mysql_script.sh
RUN chmod 744 /files/mysql_script.sh

EXPOSE 3306

CMD /bin/sh -c "/files/mysql_script.sh"
