apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: wp
spec:
  selector:
    app: wp
    tier: mysql
  type: ClusterIP
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql-image
          imagePullPolicy: Never
          env:  
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
