apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  labels:
    app: wp
spec:
  accessModes:
    - ReadWrteOnse
    resources:
      requests:
        storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName:
manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWrteOnse
  hostPath:
    path:"/mnt/data_mysql"
