apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    # tier: wp
spec:
  selector:
    app: mysql
    # tier: wp
  type: ClusterIP
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
    # tier: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      # tier: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        # tier: wp
    spec:
      containers:
        - name: mysql-container
          image: mysql-image
          imagePullPolicy: Never
          env:  
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: sys-cgroup
              mountPath: /sys/fs/cgroup
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: sys-cgroup
          hostPath:
            path: /sys/fs/cgroup
