apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWrteOnse
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: "/Users/gkarina/data_mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - 

