apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: FTP
      port: 21
      targetPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
