apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: data-port
      port: 20
      targetPort: 20
    - protocol: TCP
      name: chroot-port
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passive-port
      port: 60000
      targetPort: 60000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps-container
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 60000
          # volumeMounts:
          #   - name: ftps-storage
          #     mountPath: /var/lib/
      # volumes:
        # - name: ftps-storage
          # persistentVolumeClaim:
          #   claimName: ftps-pvc
