apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.64.200/32
      # - 192.168.99.200/32
          # - 192.168.99.100-192.168.99.200
