apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: wp
    tier: mysql
  labels:
    app: php
    tier: mysql
spec:
  # storageClassName: manual
  capacity:
    storage: 500Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  # local:
  #   path: "/mnt/data_mariadb"
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpression:
  #       - key: kubernetes.io/hostname
  #         operator: On
  #         values:
  #         - my-node
  nfs:
    server: 192.168.64.200
    path: "/var/lib/mysql"
  # hostPath:
  #   path: "/mnt/data_mariadb"
