apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: manual
  storageClassName: local-storage
  local:
    path: "/mnt/influx"
  claimRef:
    name: influx-pvc
    namespace: influx
  # hostPath:
  #   path: "/mnt/data-influx"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - influx-node
