apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/influx-data"
  # claimRef:
  #   name: influx-pvc
  #   namespace: influx
  # hostPath:
  #   path: "/mnt/data-influx"
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - influx-node
