apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/mysql-data"
  # local:
  #   path: "/mnt/data_mariadb"
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpression:
  #       - key: kubernetes.io/hostname
  #         operator: On
  #         values:
  #         - my-node
  # nfs:
  #   server: 192.168.64.200
  #   path: "/var/lib/mysql"
