# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile_wp                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gkarina <gkarina@student.21-school.ru>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/15 23:54:58 by gkarina           #+#    #+#              #
#    Updated: 2020/12/15 23:54:58 by gkarina          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add wget tar nginx supervisor

RUN apk add php php-fpm php-opcache
RUN apk add php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip php-json php-zlib php-mysqli php-phar php-bz2 curl
RUN apk add openrc

RUN mkdir -p /run/nginx/ && mkdir -p /var/www/wordpress

RUN wget https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar && mv wp-cli.phar /bin/wp

# copy nginx.conf
COPY ./srcs_wp/wp-nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod 744 /etc/nginx/conf.d/default.conf

# copy supervisord.conf
COPY ./srcs_wp/supervisord.conf /etc/supervisord.conf
RUN chmod 744 /etc/supervisord.conf

# copy config
COPY ./srcs_wp/wp-config-sample.php /var/www/wordpress/wp-config.php
RUN chmod 744 /var/www/wordpress/wp-config.php

# copy script
RUN mkdir /files
COPY ./srcs_wp/wp_script.sh /files/wp_script.sh
RUN chmod 744 /files/wp_script.sh

# VOLUME /var/www/html

RUN rc-update add php-fpm7 default && rc-update add nginx default

EXPOSE 5050

CMD /bin/sh -c "/files/wp_script.sh"
