apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  labels:
    app: wp
    tier: frontend
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.64.200
    # Exported path of your NFS server
    path: "/var/www/html"
