# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile_php                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gkarina <gkarina@student.21-school.ru>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/15 23:54:42 by gkarina           #+#    #+#              #
#    Updated: 2020/12/15 23:54:42 by gkarina          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add wget nginx supervisor

RUN apk add php php-fpm php-opcache
RUN apk add lighttpd php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom php7-session php7-mbstring
RUN apk add mysql mysql-client php-mysqli openrc

RUN mkdir -p /run/nginx/

# install php
RUN mkdir -p /var/www/html/
RUN wget -O /var/www/phpmyadmin.zip https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.zip
RUN unzip /var/www/phpmyadmin.zip -d /var/www/
RUN mv /var/www/phpMyAdmin-5.0.2-all-languages /var/www/phpmyadmin && \
	rm -rf /var/www/phpmyadmin.zip && chmod -R 777 /var/www/phpmyadmin/

# copy nginx.conf
COPY ./srcs_php/php-nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod 744 /etc/nginx/conf.d/default.conf

# copy supervisord.conf
COPY ./srcs_php/supervisord.conf /etc/supervisord.conf
RUN chmod 744 /etc/supervisord.conf

# copy config
COPY ./srcs_php/config.inc.php /var/www/phpmyadmin/config.inc.php
RUN chmod 744 /var/www/phpmyadmin/config.inc.php

# copy script
RUN mkdir /files
COPY ./srcs_php/php_script.sh /files/php_script.sh
RUN chmod 744 /files/php_script.sh

# VOLUME /var/www/html

EXPOSE 5000

CMD /bin/sh -c "/files/php_script.sh"
