apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: php
spec:
  selector:
    app: wp
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: frontend
    spec:
      containers:
        - name: php-container
          image: php-image
          imagePullPolicy: Never
          env:
            - name: PMA_HOST
              value: mysql-svc
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: password
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
