apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: php
    # tier: wp
spec:
  selector:
    app: php
    # tier: wp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: php
    # tier: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      # tier: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        # tier: wp
    spec:
      containers:
        - name: php-container
          image: php-image
          imagePullPolicy: Never
          env:
            # - name: PMA_ARBITRARY
              # value: '1'
            # - name: PMA_HOST
            #   value: mysql-svc
            # - name: PMA_USER
            #   value: gkarina_user
            # - name: PMA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-user-pass
            #       key: password
            # - name: MYSQL_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-root-pass
            #       key: password
          ports:
            - containerPort: 5000
          # volumeMounts:
          #   - name: php-storage
          #     mountPath: /var/www/html
          #   # - name: dockersock
          #   #   mountPath: /var/run/docker.sock
      # volumes:
        # - name: php-storage
          # persistentVolumeClaim:
          #   claimName: mysql-pvc
        # - name: dockersock
        #   hostPath:
        #     path: /var/run/docker.sock
