# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile_grafana                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gkarina <gkarina@student.21-school.ru>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/15 23:53:29 by gkarina           #+#    #+#              #
#    Updated: 2020/12/15 23:53:29 by gkarina          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

RUN apk update && apk upgrade

# install grafana
RUN wget -O grafana.tar.gz https://dl.grafana.com/oss/release/grafana-7.3.1.linux-amd64.tar.gz
RUN tar -zxvf grafana.tar.gz && \
	rm -rf grafana.tar.gz
RUN mv /grafana-7.3.1 /grafana

COPY ./srcs_grafana/custom.ini /grafana/conf/custom.ini

# install glibc
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
	wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk  && \
	wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-bin-2.32-r0.apk && \
	wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-i18n-2.32-r0.apk

RUN apk add glibc-2.32-r0.apk
RUN rm -f /usr/glibc-compat/lib/ld-linux-x86-64.so.2
RUN ln -svf ld-2.32.so /usr/glibc-compat/lib/ld-linux-x86-64.so.2
RUN apk add glibc-bin-2.32-r0.apk glibc-i18n-2.32-r0.apk 
RUN /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8

COPY ./srcs_grafana/sample.yaml grafana/conf/provisioning/datasources/sample.yaml

RUN mkdir /files
COPY ./srcs_grafana/grafana_script.sh /files/grafana_script.sh
RUN chmod 744 /files/grafana_script.sh
RUN ln -svf /grafana/bin/grafana-server /usr/sbin/grafana-server

RUN mkdir -p /var/lib/grafana && mkdir -p /var/log/grafana
VOLUME /var/lib/grafana

EXPOSE 3000

CMD /bin/sh -c "/files/grafana_script.sh"
