apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: grafana-port
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - name: grafana-port
          containerPort: 3000
        env:
          - name: 
