FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add wget tar

RUN mkdir -p /var/www/wordpress/
RUN wget -O wordpress.tar.gz https://wordpress.org/latest.tar.gz
RUN tar -C /var/www/ -xzvf /wordpress.tar.gz
RUN rm -rf /wordpress.tar.gz
COPY ./srcs_wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

EXPOSE 5000
CMD /bin/sh tail -f /dev/null
