FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add wget tar

RUN mkdir -p /wordpress/ && mkdir -p /files/
RUN wget -O wordpress.tar.gz https://wordpress.org/latest.tar.gz
RUN tar -C /wordpress/ -xzvf /wordpress.tar.gz
RUN rm -rf /wordpress.tar.gz
COPY ./srcs_wordpress/wp-config-sample.php /wordpress/wp-config.php
COPY ./srcs_wordpress/wp_script.sh /files/wp_script.sh
RUN chmod 744 /wordpress/wp-config.php && chmod 744 /files/wp_script.sh

EXPOSE 5000
CMD /bin/sh -c "/files/wp_script.sh"
