apiVersion: v1
kind: Service
metadata:
  name: wp-svc
spec:
  selector:
    app: wp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wp-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        - containerPort: 3306
