FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add wget

RUN mkdir -p /var/www/phpmyadmin/
RUN wget -O phpmyadmin.zip https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.zip
RUN unzip /phpmyadmin.zip -d /var/www/phpmyadmin/
RUN rm -rf /phpmyadmin.zip
COPY ./srcs_phpmyadmin/config.inc.php /var/www/phpmyadmin/config.inc.php
RUN chmod +u /var/www/phpmyadmin/config.inc.php
#RUN chown -R www-data:www-data /var/www/phpmyadmin/

EXPOSE 5050

CMD /bin/sh tail -f /dev/null
