FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add nginx openssh supervisor
RUN apk add --update util-linux

RUN mkdir -p /etc/nginx/ssl/ && mkdir -p /run/nginx/ && mkdir -p /var/run/sshd/
COPY ./srcs_nginx/nginx.crt ./srcs_nginx/nginx.key /etc/nginx/ssl/

COPY ./srcs_nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./srcs_nginx/nginx.sh /files/
COPY ./srcs_nginx/supervisord.conf /etc/supervisord.conf
COPY ./srcs_nginx/sshd_config /etc/ssh/sshd_config
RUN chmod 744 /files/nginx.sh && chmod 744 /etc/nginx/conf.d/default.conf && \
	chmod 744 /etc/supervisord.conf && chmod 744 /etc/ssh/sshd_config

# create new user
RUN adduser gkarina -D
RUN echo -e "gkarina42\ngkarina42" | passwd gkarina

# create .ssh/ dir and copy key.pub in /.ssh/autorized_keys
RUN mkdir -p /home/gkarina/.ssh/
RUN chmod 0700 /home/gkarina/.ssh/
RUN touch /home/gkarina/.ssh/authorized_keys
COPY ./srcs_nginx/gkarina_id_rsa.pub /home/gkarina/gkarina_id_rsa.pub
RUN cat /home/gkarina/gkarina_id_rsa.pub >> /home/gkarina/.ssh/authorized_keys
RUN chmod 600 /home/gkarina/.ssh/authorized_keys && rm -rf /home/gkarina/gkarina_id_rsa.pub

EXPOSE 80 443 22
CMD /bin/sh -c "/files/nginx.sh"
