FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add nginx openssh supervisor

RUN mkdir -p /etc/nginx/ssl/ && mkdir -p /run/nginx/ && mkdir -p /var/run/sshd/
COPY ./srcs_nginx/nginx.crt ./srcs_nginx/nginx.key /etc/nginx/ssl/

# create new user
RUN adduser gkarina -D
RUN echo -e "gkarina42\ngkarina42" | passwd gkarina

# copy nginx.conf
COPY ./srcs_nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod 744 /etc/nginx/conf.d/default.conf

# copy supervisord.conf
COPY ./srcs_nginx/supervisord.conf /etc/supervisord.conf
RUN chmod 744 /etc/supervisord.conf

# copy sshd_config
COPY ./srcs_nginx/sshd_config /etc/ssh/sshd_config
RUN chmod 744 /etc/ssh/sshd_config

# copy script nginx.sh
RUN mkdir -p /files/
COPY ./srcs_nginx/nginx.sh /files/
RUN chmod 744 /files/nginx.sh


# create .ssh/ dir and copy key.pub in /.ssh/autorized_keys
RUN mkdir -p /home/gkarina/.ssh/
RUN chmod 0700 /home/gkarina/.ssh/
RUN touch /home/gkarina/.ssh/authorized_keys
COPY ./srcs_nginx/gkarina.pub /home/gkarina/gkarina.pub
RUN cat /home/gkarina/gkarina.pub >> /home/gkarina/.ssh/authorized_keys
RUN chmod 600 /home/gkarina/.ssh/authorized_keys && rm -rf /home/gkarina/gkarina.pub

EXPOSE 80 443 22
CMD /bin/sh -c "/files/nginx.sh"
