apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: influx-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
