apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWrteOnse
    resources:
      requests:
        storage: 500Mi
    storageClassName: storage-class-name
