apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
  labels:
    app: influx
spec:
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  volumeName: influx-pv
