apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWrteOnse
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /Users/gkarina/data_influx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpression:
        - key: kubernetes.io/hostname
          operator: On
          values:
          - my-node

