apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: local_monitoring
  INFLUXDB_URL: http://192.168.64.200:8086
  INFLUXDB_USER: gkarina
  INFLUXDB_USER_PASSWORD: gkarina42
