apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
spec:
  selector:
    app: telegraf
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf-image
        imagePullPolicy: Never
